# Site settings
title: George for Galiano
email: george@georgeforgaliano.ca
url: https://georgeforgaliano.ca
description: "Re-elect George Harris for Galiano Island Trustee"
keywords: "george, galiano, island trust, re-elect"
skills: Experienced - Independant - Responsible
meta_author: Tyler Mauthe

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0B8472
  primary-rgb: "11,132,114"
  secondary: 1B5C7E
  secondary-dark: 1B5C7E

# Footer settings
footer:
  copyright: George Harris
  location: Location
  social: Connect With George
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/georgeforgaliano/

# Build settings
markdown: kramdown
permalink: pretty
